### ISSUE TITLE
Chart labels are not saved to the image

### ISSUE THREAD

**Issue by josedsilva** [Jeff-Tian/jquery.flot.saveAsImage.js#11]
The plugin exports only canvas data. Labels are not exported to the image. 
For e.g. for a pie chart, only the pie slices are saved as image but not the labels.
It would be nice if it was possible to export labels too.

**Comment by Jeff-Tian** [comment]
Thank you for the suggestion! Unfortunately I currently don't have time to improve it, will you use some other chart libraries that have that functionality instead?
